networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - server
      - client
    networks:
      - dev

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev

  server:
    build:
      context: .
      dockerfile: containers/server/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app #Удалить в продакшн
    networks:
      - dev

  client:
    build:
      context: .
      dockerfile: containers/client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./client:/app # Удалите в продакшене
    depends_on:
      - server  # Добавлено для синхронизации
    stdin_open: true
    tty: true
    networks:
      - dev

volumes:
  pgdata:
  # Оставляем эти сервисы для ручного запуска миграций и заполнения данных при необходимости
#  migrations:
#    build:
#      context: .
#      dockerfile: containers/server/Dockerfile
#    env_file:
#      - .env.docker
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./server:/app
#      - ./.env:/app/.env
#    command: npm run migrate
#    entrypoint: []  # Переопределяем entrypoint, чтобы не запускать весь скрипт
#    profiles: ["tools"]
#
#  seed:
#    build:
#      context: .
#      dockerfile: containers/server/Dockerfile
#    env_file:
#      - .env.docker
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./server:/app
#      - ./.env:/app/.env
#    command: npm run seed:run
#    entrypoint: []  # Переопределяем entrypoint, чтобы не запускать весь скрипт
#    profiles: ["tools"]