networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './docs/.vitepress/dist:/usr/share/nginx/html'
    depends_on:
      - server
      - client
      - docs
    networks:
      - dev

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev

  server:
    build:
      context: .
      dockerfile: containers/server/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

  client:
    build:
      context: .
      dockerfile: containers/client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - server  # Добавлено для синхронизации
    networks:
      - dev


  docs:
    build:
      context: .
      dockerfile: containers/docs/Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docs:/app/docs  # Для разработки с hot-reload
    networks:
      - dev

volumes:
  pgdata: